IF NOT EXISTS (SELECT 1 FROM SYS.TABLES WHERE NAME LIKE 'Proveedor')
BEGIN
	CREATE TABLE Proveedor (
		Id INT IDENTITY(1,1),
		Nombre VARCHAR(50) NOT NULL,
		Telefono VARCHAR(50),
		Correo VARCHAR(50),
		CONSTRAINT pk_Proveedor PRIMARY KEY (Id)
	);
END