IF EXISTS (SELECT 1 FROM SYS.TABLES WHERE NAME LIKE 'venta')
BEGIN
	ALTER TABLE Venta DROP CONSTRAINT fk_Venta_Articulo;

	TRUNCATE TABLE Articulo;

	ALTER TABLE Venta ADD CONSTRAINT fk_Venta_Articulo 
	FOREIGN KEY (ArticuloId) REFERENCES Articulo (Id)
END