//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ferreteria.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FerreteriaEntities : DbContext
    {
        
        public const string ConnectionString = "name=FerreteriaEntities";
        public const string ContainerName = "FerreteriaEntities";
    
    
        public FerreteriaEntities()
            : base("name=FerreteriaEntities")
        {
        }
    
        public FerreteriaEntities(string connectionString)
       : base(connectionString)
       {
          }
    
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Articulo> Articulos { get; set; }
        public virtual DbSet<Categoria> Categorias { get; set; }
        public virtual DbSet<Empleado> Empleados { get; set; }
        public virtual DbSet<Local> Locales { get; set; }
        public virtual DbSet<Puesto> Puestos { get; set; }
        public virtual DbSet<Venta> Ventas { get; set; }
    }
}
